/*
 * This source file was generated by the Gradle 'init' task
 */
package org.APCSLowell;

public class GoogleBillboard {
    public boolean isPrime(long num) {
  if(num <= 1 || num%1 !=0){
    return false;
  }
  for(int i = 2; i<= Math.sqrt(num); i++){
    if(num%i==0){
      return false;
    }
  }
  return true;
    }
    public long firstPrimeNumberIn(String n) {
        for(int i = 0; i<n.length()-10; i++){
            String sub = n.substring(i, i+10);
            long value = Long.parseLong(sub);
            if(isPrime(value)){
                return value;
            }
        }
        return -1;
    }
}
